export const ActionTypes = {
  GET_EVENT_REQUEST: "GET_EVENT_REQUEST",
  GET_EVENT_REQUEST_SUCCESS: "GET_EVENT_REQUEST_SUCCESS",
  GET_EVENT_REQUEST_FAILURE: "GET_EVENT_REQUEST_FAILURE",
  SET_ADMIN_CONTENT: "SET_ADMIN_CONTENT",
  SET_ADMIN_Request: "SET_ADMIN_Request",
  SET_ADMIN_Success: "SET_ADMIN_Success",
  SET_ADMIN_Failure: "SET_ADMIN_Failure",
  SET_MEMBER_Request: "SET_MEMBER_Request",
  SET_MEMBER_Success: "SET_MEMBER_Success",
  SET_MEMBER_Failure: "SET_MEMBER_Failure",
}
