export const ActionTypes = {
  GET_EVENT_REQUEST: "GET_EVENT_REQUEST",
  GET_EVENT_REQUEST_SUCCESS: "GET_EVENT_REQUEST_SUCCESS",
  GET_EVENT_REQUEST_FAILURE: "GET_EVENT_REQUEST_FAILURE",
  SET_FILTERING: "SET_FILTERING",
  GET_EVENTS_LIST: "GET_EVENTS_LIST",
  SEND_FILTER_REQUEST: "Send_Filter_Request",
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  EDIT_TASK: "EDIT_TASK",
  CHANGE_STATUS: "CHANGE_STATUS",
  ASSIGN_MEMBER: "ASSIGN_MEMBER",
  SELECT_SUBTASK: "SELECT_SUBTASK",
  REMOVE_TASK_MEMBER: "REMOVE_TASK_MEMBER",
  RESET_FILTERED_EVENTS: "RESET_FILTERED_EVENTS"
}
