export const ActionTypes = {
  GET_EVENT_REQUEST: "GET_EVENT_REQUEST",
  GET_EVENT_REQUEST_SUCCESS: "GET_EVENT_REQUEST_SUCCESS",
  GET_EVENT_REQUEST_FAILURE: "GET_EVENT_REQUEST_FAILURE",
  SET_ADMIN_CONTENT: "SET_ADMIN_CONTENT"
}
